<?php
$title = "Pooling Demo";
$this->headTitle($title);
?>
<?php $counter=0; foreach ($poolcounts as $poolcount) :
     $counter = $counter + 1;
endforeach; ?>
<table width="100%">
<tr>
<td valign="top">
     <h1 style="text-indent: 0.2cm;">Total Voters:&nbsp;<?php echo $counter; ?></h1>
     <p style="text-indent: 0.4cm;">
     <a href="<?php echo $this->url('pool', array('action'=>'choose'));?>"><font style="font-size:16px;">Choose your favorite browser</font></a>
</p>
</td>
<td style="float:right; padding-right:100px;">
     <dl style="width: 350px">
     <!-- <dd><div id="data-one" class="bar" style="width: 60%">Chrome - 60%</div></dd>
     <dt>2009</dt>
     <dd><div id="data-two" class="bar" style="width: 80%">Safari - 80%</div></dd>
     <dt>2010</dt>
     <dd><div id="data-three" class="bar" style="width: 64%">Firefox- 64%</div></dd>
     <dt>2011</dt>
     <dd><div id="data-four" class="bar" style="width: 97%">IExplorer - 97%</div></dd> -->
     <?php foreach ($records as $record) : ?>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->Chrome); ?></div></dd>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->Safari); ?></div></dd>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->Firefox); ?></div></dd>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->IExplorer); ?></div></dd>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->Opera); ?></div></dd>
     <dd><div id="data-one" class="bar" style="width: 60%">Chrome - <?php echo $this->excapeHtml($record->Lynx); ?></div></dd>
     <?php endforeach; ?>
     </dl>
</td>
</tr>
</table>

<dl class="sub-nav">
<dt>Filter:</dt>
<dd class="active"><a href="<?php echo $this->url('pool');?>">All</a></dd>
<dd><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'Chrome'));?>">Chrome</a></dd>
<dd><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'Safari'));?>">Safari</a></dd>
<dd><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'Firefox'));?>">Firefox</a></dd>
<dd><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'IExplorer'));?>">IExplorer</a></dd>
<dd><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'Opera'));?>">Opera</a></dd>
<dd class-"hide-for-small-only"><a href="<?php echo $this->url('pool', array('action'=>'browser', 'id' => 'Lynx'));?>">Lynx</a></dd>
</dl>
 <table class="table">
 <tr>
     <th>Name</th>
     <th>Email</th>
     <th>Browser</th>
     <th>Reason</th>
     <th>Time Voted</th>
 </tr>
 <?php foreach ($pools as $pool) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($pool->name);?></td>
     <td><?php echo $this->escapeHtml($pool->emailadd);?></td>
     <td><?php echo $this->escapeHtml($pool->browser);?></td>
     <td><?php echo $this->escapeHtml($pool->reason);?></td>
     <td><?php echo $this->escapeHtml($pool->timevote);?></td>
 </tr>
 <?php endforeach; ?>
 </table>
 